version: '3.2'

services:
  sid_umag_culturales_deportivos_front:
    container_name: SID-UMAG-ESTUDIANTE-Culturales-Deportivos-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUXT_SESSION_SESSION_STORAGE_OPTIONS_OPTIONS_URL=${NUXT_SESSION_SESSION_STORAGE_OPTIONS_OPTIONS_URL}
    expose:
      - 3000
    env_file:
      - .env
    networks:
      - umag_network
    restart: always
    labels:
      #- "traefik.enable=true"
      - "traefik.http.routers.sid_umag_cdeportivos_front.rule=Host(`sid.pichimalen.org`) && (PathPrefix(`/culturales-deportivos`) || PathPrefix(`/api/culturales-deportivos/session`))"
      #- "traefik.http.routers.sid_umag_cdeportivos_front.entrypoints=websecure"
      #- "traefik.http.routers.sid_umag_cdeportivos_front.tls=true"
      # - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.services.sid_umag_cdeportivos_front.loadbalancer.server.port=3000"
      #- "traefik.http.routers.sid_umag_cdeportivos_front.service=sid_umag_cdeportivos_front"
      - "traefik.http.routers.sid_umag_cdeportivos_front.middlewares=redirect-to-session@file"

networks:
  umag_network:
    external: true